# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ros1_bridge_support_pkg/MyCustomMessage.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class MyCustomMessage(genpy.Message):
  _md5sum = "c00790425d14a25b56563df5c8c07bbd"
  _type = "ros1_bridge_support_pkg/MyCustomMessage"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """## file 'MyCustomMessage.msg'

bool value_boolean
int32 value_integer
float32 value_float
string value_string
"""
  __slots__ = ['value_boolean','value_integer','value_float','value_string']
  _slot_types = ['bool','int32','float32','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       value_boolean,value_integer,value_float,value_string

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MyCustomMessage, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.value_boolean is None:
        self.value_boolean = False
      if self.value_integer is None:
        self.value_integer = 0
      if self.value_float is None:
        self.value_float = 0.
      if self.value_string is None:
        self.value_string = ''
    else:
      self.value_boolean = False
      self.value_integer = 0
      self.value_float = 0.
      self.value_string = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_Bif().pack(_x.value_boolean, _x.value_integer, _x.value_float))
      _x = self.value_string
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.value_boolean, _x.value_integer, _x.value_float,) = _get_struct_Bif().unpack(str[start:end])
      self.value_boolean = bool(self.value_boolean)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.value_string = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.value_string = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_Bif().pack(_x.value_boolean, _x.value_integer, _x.value_float))
      _x = self.value_string
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.value_boolean, _x.value_integer, _x.value_float,) = _get_struct_Bif().unpack(str[start:end])
      self.value_boolean = bool(self.value_boolean)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.value_string = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.value_string = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_Bif = None
def _get_struct_Bif():
    global _struct_Bif
    if _struct_Bif is None:
        _struct_Bif = struct.Struct("<Bif")
    return _struct_Bif
